version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    tty: true
    volumes:
      - ./:/go/src/github.com/toshiykst/golang-rest-api
    ports:
      - "8080:8080"
