version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golang_rest_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
