CREATE DATABASE IF NOT EXISTS golang_rest_api;
USE golang_rest_api;

CREATE TABLE IF NOT EXISTS posts (
  id          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title       VARCHAR(255) NOT NULL,
  content     VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;